[2024-08-18T07:16:49.323+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:16:49.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:16:49.329+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:16:49.329+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:16:49.408+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:16:49.397+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:16:49.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:16:49.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.134 seconds
[2024-08-18T07:17:20.009+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:20.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:17:20.013+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:17:20.013+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:20.047+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:17:20.041+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:17:20.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:20.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.096 seconds
[2024-08-18T07:17:51.890+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:51.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:17:51.899+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:17:51.898+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:51.988+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:17:51.973+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:17:51.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:17:52.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.227 seconds
[2024-08-18T07:18:22.562+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:22.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:18:22.567+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:18:22.567+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:22.625+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:18:22.616+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:18:22.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:22.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.142 seconds
[2024-08-18T07:18:53.227+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:53.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:18:53.234+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:18:53.233+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:53.278+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:18:53.270+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:18:53.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:18:53.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-08-18T07:19:24.701+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:24.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:19:24.705+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:19:24.705+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:24.735+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:19:24.729+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:19:24.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:24.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.083 seconds
[2024-08-18T07:19:55.467+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:55.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:19:55.477+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:19:55.476+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:55.540+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:19:55.529+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:19:55.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:19:55.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.179 seconds
[2024-08-18T07:20:26.476+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:26.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:20:26.479+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:20:26.479+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:26.508+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:20:26.502+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:20:26.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:26.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.087 seconds
[2024-08-18T07:20:57.780+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:57.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:20:57.784+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:20:57.783+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:57.877+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:20:57.816+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:20:57.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:20:57.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.180 seconds
[2024-08-18T07:21:28.809+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:21:28.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:21:28.811+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:21:28.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:21:28.837+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:21:28.832+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:21:28.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:21:28.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.080 seconds
[2024-08-18T07:22:00.265+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:00.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:22:00.271+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:22:00.270+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:00.326+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:22:00.315+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:22:00.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:00.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.158 seconds
[2024-08-18T07:22:31.342+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:31.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:22:31.345+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:22:31.344+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:31.373+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:22:31.366+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:22:31.375+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:22:31.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.086 seconds
[2024-08-18T07:23:02.388+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:02.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:23:02.393+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:23:02.392+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:02.528+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:23:02.516+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:23:02.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:02.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.233 seconds
[2024-08-18T07:23:32.970+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:32.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:23:32.973+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:23:32.973+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:33.000+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:23:32.995+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:23:33.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:23:33.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.082 seconds
[2024-08-18T07:24:03.621+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:03.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:24:03.625+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:24:03.624+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:03.684+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:24:03.670+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:24:03.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:03.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.152 seconds
[2024-08-18T07:24:35.078+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:35.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:24:35.082+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:24:35.081+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:35.128+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:24:35.116+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:24:35.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:24:35.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.191 seconds
[2024-08-18T07:25:06.033+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:06.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:25:06.039+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:25:06.038+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:06.106+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:25:06.085+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:25:06.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:06.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.194 seconds
[2024-08-18T07:25:36.724+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:36.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:25:36.728+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:25:36.727+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:36.796+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:25:36.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:25:36.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:25:36.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.155 seconds
[2024-08-18T07:26:07.801+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:07.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:26:07.804+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:26:07.804+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:07.863+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:26:07.848+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:26:07.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:07.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.149 seconds
[2024-08-18T07:26:39.713+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:39.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:26:39.723+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:26:39.722+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:39.821+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:26:39.806+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:26:39.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:26:39.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.228 seconds
[2024-08-18T07:27:10.373+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:10.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:27:10.378+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:27:10.377+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:10.421+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:27:10.411+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:27:10.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:10.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.126 seconds
[2024-08-18T07:27:40.780+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:40.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:27:40.784+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:27:40.783+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:40.819+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:27:40.813+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:27:40.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:27:40.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.104 seconds
[2024-08-18T07:28:12.152+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:12.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:28:12.156+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:28:12.155+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:12.192+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:28:12.187+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:28:12.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:12.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.108 seconds
[2024-08-18T07:28:43.318+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:43.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:28:43.323+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:28:43.323+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:43.352+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:28:43.347+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:28:43.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:28:43.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.088 seconds
[2024-08-18T07:29:14.269+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:14.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:29:14.273+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:29:14.272+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:14.334+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:29:14.319+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:29:14.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:14.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.163 seconds
[2024-08-18T07:29:45.172+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:45.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:29:45.177+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:29:45.176+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:45.211+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:29:45.205+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:29:45.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:29:45.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.358 seconds
[2024-08-18T07:30:16.950+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:16.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:30:16.954+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:30:16.953+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:17.023+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:30:17.010+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:30:17.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:17.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.172 seconds
[2024-08-18T07:30:49.176+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:49.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:30:49.180+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:30:49.179+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:49.231+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:30:49.220+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:30:49.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:30:49.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.142 seconds
[2024-08-18T07:31:20.687+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:20.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:31:20.691+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:31:20.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:20.762+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:31:20.747+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:31:20.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:20.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.175 seconds
[2024-08-18T07:31:51.984+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:51.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:31:51.990+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:31:51.989+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:52.066+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:31:52.051+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:31:52.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:31:52.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.188 seconds
[2024-08-18T07:32:23.544+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:23.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:32:23.549+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:32:23.549+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:23.617+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:32:23.605+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:32:23.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:23.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.180 seconds
[2024-08-18T07:32:54.208+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:54.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:32:54.212+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:32:54.212+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:54.257+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:32:54.249+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:32:54.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:32:54.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.120 seconds
[2024-08-18T07:33:24.798+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:24.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:33:24.801+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:33:24.801+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:24.842+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:33:24.833+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:33:24.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:24.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.122 seconds
[2024-08-18T07:33:56.187+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:56.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:33:56.195+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:33:56.194+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:56.264+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:33:56.252+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:33:56.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:33:56.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.178 seconds
[2024-08-18T07:34:26.851+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:26.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:34:26.855+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:34:26.854+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:26.906+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:34:26.895+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:34:26.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:26.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.135 seconds
[2024-08-18T07:34:57.529+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:57.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:34:57.534+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:34:57.534+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:57.605+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:34:57.589+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:34:57.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:34:57.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.192 seconds
[2024-08-18T07:35:28.864+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:28.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:35:28.873+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:35:28.873+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:29.006+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:35:28.996+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:35:29.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:29.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.255 seconds
[2024-08-18T07:35:59.595+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:59.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:35:59.600+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:35:59.599+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:59.666+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:35:59.650+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:35:59.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:35:59.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.183 seconds
[2024-08-18T07:36:30.445+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:36:30.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:36:30.449+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:36:30.449+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:36:30.497+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:36:30.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:36:30.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:36:30.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.139 seconds
[2024-08-18T07:37:01.296+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:01.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:37:01.301+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:01.300+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:01.386+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:01.367+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:37:01.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:01.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.220 seconds
[2024-08-18T07:37:31.954+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:31.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:37:31.958+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:31.958+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:32.025+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:32.014+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:37:32.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:37:32.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.146 seconds
[2024-08-18T07:38:03.537+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:03.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:38:03.543+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:03.542+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:03.591+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:03.581+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:38:03.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:03.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.153 seconds
[2024-08-18T07:38:34.663+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:34.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:38:34.667+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:34.666+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:34.711+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:34.699+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:38:34.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:38:34.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.143 seconds
[2024-08-18T07:39:06.024+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:06.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:39:06.029+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:06.028+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:06.108+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:06.092+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:39:06.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:06.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.193 seconds
[2024-08-18T07:39:36.717+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:36.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:39:36.722+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:36.721+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:36.770+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:36.758+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:39:36.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:39:36.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.157 seconds
[2024-08-18T07:40:08.287+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:08.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:40:08.293+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:08.292+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:08.380+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:08.362+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:40:08.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:08.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.213 seconds
[2024-08-18T07:40:39.540+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:39.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:40:39.546+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:39.545+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:39.614+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:39.599+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:40:39.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:40:39.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.177 seconds
[2024-08-18T07:41:10.763+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:10.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:41:10.767+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:10.767+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:10.814+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:10.803+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:41:10.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:10.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.143 seconds
[2024-08-18T07:41:41.817+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:41.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:41:41.831+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:41.830+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:41.891+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:41.881+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:41:41.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:41:41.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-08-18T07:42:12.741+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:12.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:42:12.748+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:12.747+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:12.811+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:12.797+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:42:12.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:12.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.179 seconds
[2024-08-18T07:42:43.489+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:43.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:42:43.494+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:43.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:43.552+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:43.539+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:42:43.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:42:43.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.155 seconds
[2024-08-18T07:43:15.216+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:15.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:43:15.220+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:15.220+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:15.289+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:15.273+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:43:15.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:15.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-08-18T07:43:46.399+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:46.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:43:46.407+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:46.407+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:46.461+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:46.445+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:43:46.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:43:46.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.161 seconds
[2024-08-18T07:44:16.970+0000] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:16.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:44:16.977+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:16.976+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:17.038+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:17.026+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:44:17.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:17.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.193 seconds
[2024-08-18T07:44:48.939+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:48.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:44:48.943+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:48.943+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:49.011+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:48.995+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:44:49.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:44:49.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.180 seconds
[2024-08-18T07:45:20.033+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:20.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:45:20.038+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:20.038+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:20.093+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:20.084+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:45:20.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:20.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.193 seconds
[2024-08-18T07:45:50.603+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:50.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:45:50.608+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:50.607+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:50.687+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:50.668+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:45:50.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:45:50.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.213 seconds
[2024-08-18T07:46:22.232+0000] {processor.py:186} INFO - Started process (PID=530) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:22.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:46:22.238+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:22.236+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:22.317+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:22.304+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:46:22.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:22.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.175 seconds
[2024-08-18T07:46:53.666+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:53.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:46:53.672+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:53.671+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:53.719+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:53.709+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:46:53.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:46:53.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.136 seconds
[2024-08-18T07:47:24.989+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:24.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:47:24.993+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:24.993+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:25.052+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:25.041+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:47:25.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:25.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.137 seconds
[2024-08-18T07:47:56.244+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:56.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:47:56.250+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:56.249+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:56.307+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:56.293+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:47:56.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:47:56.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.149 seconds
[2024-08-18T07:48:27.376+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:27.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:48:27.381+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:27.380+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:27.453+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:27.434+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:48:27.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:27.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.166 seconds
[2024-08-18T07:48:58.504+0000] {processor.py:186} INFO - Started process (PID=590) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:58.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:48:58.508+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:58.508+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:58.565+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:58.554+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:48:58.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:48:58.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.164 seconds
[2024-08-18T07:49:29.346+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:49:29.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:49:29.348+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:29.348+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:49:29.370+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:29.366+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:49:29.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:49:29.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.105 seconds
[2024-08-18T07:50:00.452+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:00.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:50:00.457+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:00.456+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:00.520+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:00.510+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:50:00.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:00.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.154 seconds
[2024-08-18T07:50:31.248+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:31.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:50:31.253+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:31.253+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:31.316+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:31.303+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:50:31.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:50:31.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.166 seconds
[2024-08-18T07:51:02.344+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:02.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:51:02.348+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:02.348+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:02.412+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:02.399+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:51:02.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:02.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.159 seconds
[2024-08-18T07:51:33.674+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:33.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:51:33.678+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:33.678+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:33.746+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:33.733+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:51:33.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:51:33.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.165 seconds
[2024-08-18T07:52:04.481+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:04.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:52:04.486+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:04.485+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:04.555+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:04.541+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:52:04.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:04.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.168 seconds
[2024-08-18T07:52:36.866+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:36.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:52:36.870+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:36.870+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:36.932+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:36.919+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:52:36.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:52:37.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.157 seconds
[2024-08-18T07:53:09.539+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:09.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:53:09.542+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:09.542+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:09.612+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:09.597+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:53:09.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:09.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.165 seconds
[2024-08-18T07:53:40.367+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:40.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:53:40.372+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:40.371+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:40.437+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:40.420+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:53:40.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:53:40.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-08-18T07:54:11.426+0000] {processor.py:186} INFO - Started process (PID=726) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:11.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:54:11.430+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:11.430+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:11.488+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:11.477+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:54:11.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:11.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.159 seconds
[2024-08-18T07:54:43.356+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:43.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:54:43.361+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:43.360+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:43.420+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:43.406+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:54:43.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:54:43.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-08-18T07:55:14.772+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:14.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:55:14.779+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:14.776+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:14.809+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:14.804+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:55:14.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:14.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.110 seconds
[2024-08-18T07:55:46.798+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:46.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:55:46.800+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:46.800+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:46.822+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:46.816+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:55:46.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:55:46.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.082 seconds
[2024-08-18T07:56:17.842+0000] {processor.py:186} INFO - Started process (PID=786) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:17.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:56:17.847+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:17.846+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:17.914+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:17.899+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:56:17.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:18.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.172 seconds
[2024-08-18T07:56:51.637+0000] {processor.py:186} INFO - Started process (PID=802) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:51.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:56:51.643+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:51.642+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:51.691+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:51.679+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:56:51.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:56:51.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-08-18T07:57:23.101+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:23.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:57:23.108+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:23.108+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:23.166+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:23.152+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:57:23.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:23.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.187 seconds
[2024-08-18T07:57:55.499+0000] {processor.py:186} INFO - Started process (PID=834) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:55.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:57:55.508+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:55.507+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:55.566+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:55.555+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:57:55.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:57:55.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.179 seconds
[2024-08-18T07:58:26.794+0000] {processor.py:186} INFO - Started process (PID=850) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:58:26.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:58:26.797+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:26.797+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:58:26.858+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:26.844+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:58:26.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:58:26.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.154 seconds
[2024-08-18T07:58:59.964+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:58:59.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:58:59.969+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:59.968+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:59:00.011+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:00.003+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:59:00.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:59:00.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.156 seconds
[2024-08-18T07:59:31.338+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:59:31.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:59:31.343+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:31.342+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:59:31.385+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:31.375+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:59:31.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T07:59:31.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.141 seconds
[2024-08-18T08:00:02.576+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:02.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:00:02.579+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:02.578+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:02.639+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:02.625+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:00:02.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:02.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.157 seconds
[2024-08-18T08:00:34.256+0000] {processor.py:186} INFO - Started process (PID=914) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:34.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:00:34.261+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:34.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:34.329+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:34.314+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:00:34.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:00:34.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.177 seconds
[2024-08-18T08:01:05.769+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:05.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:01:05.773+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:05.773+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:05.831+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:05.818+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:01:05.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:05.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-08-18T08:01:36.044+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:36.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:01:36.048+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:36.047+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:36.108+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:36.094+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:01:36.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:01:36.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.152 seconds
[2024-08-18T08:02:08.385+0000] {processor.py:186} INFO - Started process (PID=964) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:08.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:02:08.388+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:08.387+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:08.414+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:08.409+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:02:08.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:08.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.099 seconds
[2024-08-18T08:02:39.754+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:39.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:02:39.758+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:39.758+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:39.826+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:39.811+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:02:39.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:02:39.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.162 seconds
[2024-08-18T08:03:11.160+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:11.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:03:11.165+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:11.163+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:11.226+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:11.213+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:03:11.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:11.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.175 seconds
[2024-08-18T08:03:41.820+0000] {processor.py:186} INFO - Started process (PID=1018) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:41.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:03:41.825+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:41.823+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:41.897+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:41.879+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:03:41.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:03:41.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-08-18T08:04:12.897+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:12.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:04:12.901+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:12.900+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:12.948+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:12.940+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:04:12.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:13.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.122 seconds
[2024-08-18T08:04:44.581+0000] {processor.py:186} INFO - Started process (PID=1054) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:44.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:04:44.585+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:44.585+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:44.625+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:44.617+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:04:44.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:04:44.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.113 seconds
[2024-08-18T08:05:16.468+0000] {processor.py:186} INFO - Started process (PID=1072) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:16.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:05:16.473+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:16.472+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:16.538+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:16.523+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:05:16.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:16.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.161 seconds
[2024-08-18T08:05:48.266+0000] {processor.py:186} INFO - Started process (PID=1090) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:48.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:05:48.270+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:48.269+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:48.336+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:48.325+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:05:48.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:05:48.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.168 seconds
[2024-08-18T08:06:20.107+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:20.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:06:20.113+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:20.112+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:20.172+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:20.159+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:06:20.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:20.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.164 seconds
[2024-08-18T08:06:53.486+0000] {processor.py:186} INFO - Started process (PID=1126) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:53.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:06:53.492+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:53.491+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:53.554+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:53.541+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:06:53.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:06:53.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.177 seconds
[2024-08-18T08:07:25.424+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:25.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:07:25.431+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:25.430+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:25.470+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:25.460+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:07:25.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:25.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.148 seconds
[2024-08-18T08:07:57.464+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:57.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:07:57.468+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:57.467+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:57.529+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:57.516+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:07:57.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:07:57.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.165 seconds
[2024-08-18T08:08:28.758+0000] {processor.py:186} INFO - Started process (PID=1181) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:08:28.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:08:28.763+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:28.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:08:28.827+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:28.812+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:08:28.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:08:28.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.141 seconds
[2024-08-18T08:09:01.704+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:01.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:09:01.709+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:01.708+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:01.769+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:01.757+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:09:01.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:01.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.172 seconds
[2024-08-18T08:09:32.834+0000] {processor.py:186} INFO - Started process (PID=1217) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:32.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:09:32.839+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:32.838+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:32.880+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:32.867+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:09:32.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:09:32.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.122 seconds
[2024-08-18T08:10:04.077+0000] {processor.py:186} INFO - Started process (PID=1235) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:04.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:10:04.081+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:04.081+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:04.143+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:04.128+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:10:04.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:04.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.161 seconds
[2024-08-18T08:10:35.443+0000] {processor.py:186} INFO - Started process (PID=1253) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:35.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:10:35.449+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:35.448+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:35.501+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:35.490+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:10:35.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:10:35.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.157 seconds
[2024-08-18T08:11:09.641+0000] {processor.py:186} INFO - Started process (PID=1272) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:09.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:11:09.644+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:09.643+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:09.667+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:09.661+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:11:09.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:09.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.090 seconds
[2024-08-18T08:11:42.459+0000] {processor.py:186} INFO - Started process (PID=1290) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:42.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:11:42.462+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:42.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:42.515+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:42.504+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:11:42.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:11:42.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.148 seconds
[2024-08-18T08:12:16.954+0000] {processor.py:186} INFO - Started process (PID=1309) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:16.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:12:16.958+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:16.958+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:17.010+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:16.999+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:12:17.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:17.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.148 seconds
[2024-08-18T08:12:49.126+0000] {processor.py:186} INFO - Started process (PID=1328) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:49.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:12:49.129+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:49.128+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:49.183+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:49.169+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:12:49.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:12:49.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.147 seconds
[2024-08-18T08:13:26.597+0000] {processor.py:186} INFO - Started process (PID=1347) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:13:26.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:13:26.609+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:26.606+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:13:26.782+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:26.756+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:13:26.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:13:26.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.348 seconds
[2024-08-18T08:14:01.651+0000] {processor.py:186} INFO - Started process (PID=1366) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:14:01.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-08-18T08:14:01.654+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:14:01.654+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:14:01.718+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:14:01.703+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T08:14:01.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-08-18T08:14:01.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
