[2024-08-18T07:36:47.755+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:36:47.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:36:47.761+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:36:47.760+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:36:47.880+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:36:47.864+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:36:47.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:36:47.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.238 seconds
[2024-08-18T07:37:19.899+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:37:19.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:37:19.904+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:19.903+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:37:19.986+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:19.975+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:37:19.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:37:20.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.179 seconds
[2024-08-18T07:37:51.474+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:37:51.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:37:51.478+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:51.478+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:37:51.583+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:37:51.567+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:37:51.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:37:51.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.228 seconds
[2024-08-18T07:38:22.739+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:38:22.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:38:22.744+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:22.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:38:22.878+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:22.859+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:38:22.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:38:22.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.256 seconds
[2024-08-18T07:38:53.725+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:38:53.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:38:53.729+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:53.728+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:38:53.855+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:38:53.837+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:38:53.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:38:53.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.223 seconds
[2024-08-18T07:39:25.356+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:39:25.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:39:25.364+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:25.363+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:39:25.500+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:25.480+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:39:25.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:39:25.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.581 seconds
[2024-08-18T07:39:57.334+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:39:57.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:39:57.343+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:57.342+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:39:57.439+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:39:57.422+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:39:57.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:39:57.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.202 seconds
[2024-08-18T07:40:27.853+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:40:27.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:40:27.860+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:27.859+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:40:27.955+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:27.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:40:27.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:40:28.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.171 seconds
[2024-08-18T07:40:58.477+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:40:58.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:40:58.481+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:58.480+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:40:58.585+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:40:58.567+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:40:58.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:40:58.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.216 seconds
[2024-08-18T07:41:30.332+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:41:30.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:41:30.336+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:30.336+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:41:30.469+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:41:30.450+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:41:30.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:41:30.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.243 seconds
[2024-08-18T07:42:01.699+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:42:01.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:42:01.706+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:01.705+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:42:01.820+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:01.804+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:42:01.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:42:01.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.223 seconds
[2024-08-18T07:42:32.490+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:42:32.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:42:32.497+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:32.496+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:42:32.611+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:42:32.595+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:42:32.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:42:32.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.230 seconds
[2024-08-18T07:43:02.935+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:43:02.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:43:02.939+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:02.938+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:43:03.021+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:03.009+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:43:03.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:43:03.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.170 seconds
[2024-08-18T07:43:34.307+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:43:34.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:43:34.311+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:34.310+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:43:34.406+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:43:34.389+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:43:34.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:43:34.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.207 seconds
[2024-08-18T07:44:05.808+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:44:05.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:44:05.812+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:05.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:44:05.897+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:05.882+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:44:05.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:44:05.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.183 seconds
[2024-08-18T07:44:36.997+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:44:36.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:44:37.001+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:37.000+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:44:37.097+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:44:37.082+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:44:37.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:44:37.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.204 seconds
[2024-08-18T07:45:07.957+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:45:07.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:45:07.960+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:07.960+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:45:08.070+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:08.053+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:45:08.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:45:08.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.217 seconds
[2024-08-18T07:45:39.380+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:45:39.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:45:39.385+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:39.384+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:45:39.499+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:45:39.486+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:45:39.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:45:39.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.213 seconds
[2024-08-18T07:46:10.359+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:46:10.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:46:10.363+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:10.362+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:46:10.478+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:10.464+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:46:10.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:46:10.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.211 seconds
[2024-08-18T07:46:41.564+0000] {processor.py:186} INFO - Started process (PID=538) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:46:41.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:46:41.568+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:41.567+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:46:41.670+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:46:41.654+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:46:41.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:46:41.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.194 seconds
[2024-08-18T07:47:12.763+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:47:12.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:47:12.767+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:12.766+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:47:12.867+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:12.851+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:47:12.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:47:12.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.239 seconds
[2024-08-18T07:47:43.697+0000] {processor.py:186} INFO - Started process (PID=562) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:47:43.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:47:43.704+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:43.703+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:47:43.884+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:47:43.877+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:47:43.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:47:43.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.236 seconds
[2024-08-18T07:48:15.121+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:48:15.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:48:15.126+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:15.126+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:48:15.246+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:15.231+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:48:15.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:48:15.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.227 seconds
[2024-08-18T07:48:46.132+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:48:46.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:48:46.137+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:46.137+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:48:46.247+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:48:46.232+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:48:46.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:48:46.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.215 seconds
[2024-08-18T07:49:17.981+0000] {processor.py:186} INFO - Started process (PID=598) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:49:17.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:49:17.985+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:17.984+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:49:18.054+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:18.046+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:49:18.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:49:18.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.144 seconds
[2024-08-18T07:49:49.053+0000] {processor.py:186} INFO - Started process (PID=610) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:49:49.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:49:49.057+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:49.056+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:49:49.119+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:49:49.113+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:49:49.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:49:49.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.119 seconds
[2024-08-18T07:50:20.332+0000] {processor.py:186} INFO - Started process (PID=622) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:50:20.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:50:20.335+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:20.335+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:50:20.430+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:20.420+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:50:20.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:50:20.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.178 seconds
[2024-08-18T07:50:51.644+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:50:51.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:50:51.648+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:51.647+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:50:51.747+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:50:51.733+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:50:51.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:50:51.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.197 seconds
[2024-08-18T07:51:22.298+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:51:22.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:51:22.301+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:22.301+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:51:22.405+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:22.389+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:51:22.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:51:22.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.195 seconds
[2024-08-18T07:51:57.553+0000] {processor.py:186} INFO - Started process (PID=660) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:51:57.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:51:57.557+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:57.556+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:51:57.638+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:51:57.628+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:51:57.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:51:57.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.146 seconds
[2024-08-18T07:52:30.197+0000] {processor.py:186} INFO - Started process (PID=675) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:52:30.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:52:30.201+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:30.200+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:52:30.302+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:52:30.285+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:52:30.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:52:30.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.191 seconds
[2024-08-18T07:53:01.167+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:53:01.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:53:01.171+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:01.171+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:53:01.272+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:01.257+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:53:01.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:53:01.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.196 seconds
[2024-08-18T07:53:32.862+0000] {processor.py:186} INFO - Started process (PID=705) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:53:32.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:53:32.867+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:32.866+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:53:32.962+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:53:32.948+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:53:32.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:53:33.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.196 seconds
[2024-08-18T07:54:03.272+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:54:03.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:54:03.275+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:03.275+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:54:03.360+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:03.348+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:54:03.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:54:03.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.167 seconds
[2024-08-18T07:54:34.881+0000] {processor.py:186} INFO - Started process (PID=736) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:54:34.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:54:34.885+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:34.885+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:54:34.993+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:54:34.978+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:54:35.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:54:35.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.209 seconds
[2024-08-18T07:55:06.211+0000] {processor.py:186} INFO - Started process (PID=751) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:55:06.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:55:06.215+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:06.214+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:55:06.302+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:06.287+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:55:06.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:55:06.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.180 seconds
[2024-08-18T07:55:37.962+0000] {processor.py:186} INFO - Started process (PID=766) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:55:37.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:55:37.965+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:37.964+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:55:38.050+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:55:38.037+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:55:38.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:55:38.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.163 seconds
[2024-08-18T07:56:09.243+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:56:09.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:56:09.247+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:09.247+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:56:09.359+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:09.344+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:56:09.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:56:09.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.215 seconds
[2024-08-18T07:56:41.022+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:56:41.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:56:41.029+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:41.028+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:56:41.153+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:56:41.124+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:56:41.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:56:41.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.213 seconds
[2024-08-18T07:57:12.373+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:57:12.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:57:12.419+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:12.418+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:57:12.530+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:12.509+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:57:12.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:57:12.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.259 seconds
[2024-08-18T07:57:43.677+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:57:43.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:57:43.683+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:43.682+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:57:43.784+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:57:43.774+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:57:43.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:57:43.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.184 seconds
[2024-08-18T07:58:14.324+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:58:14.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:58:14.327+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:14.327+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:58:14.396+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:14.385+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:58:14.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:58:14.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.158 seconds
[2024-08-18T07:58:48.110+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:58:48.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:58:48.124+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:48.123+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:58:48.307+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:58:48.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:58:48.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:58:48.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.564 seconds
[2024-08-18T07:59:19.654+0000] {processor.py:186} INFO - Started process (PID=876) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:59:19.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:59:19.658+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:19.658+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:59:19.756+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:19.740+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:59:19.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:59:19.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.187 seconds
[2024-08-18T07:59:50.562+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/producer.py
[2024-08-18T07:59:50.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T07:59:50.566+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:50.565+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T07:59:50.619+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:59:50.610+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T07:59:50.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T07:59:50.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.128 seconds
[2024-08-18T08:00:21.778+0000] {processor.py:186} INFO - Started process (PID=908) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:00:21.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:00:21.781+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:21.780+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:00:21.822+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:21.815+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:00:21.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:00:21.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.099 seconds
[2024-08-18T08:00:53.137+0000] {processor.py:186} INFO - Started process (PID=924) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:00:53.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:00:53.141+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:53.140+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:00:53.242+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:00:53.230+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:00:53.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:00:53.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.184 seconds
[2024-08-18T08:01:24.570+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:01:24.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:01:24.573+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:24.573+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:01:24.673+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:24.658+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:01:24.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:01:24.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.204 seconds
[2024-08-18T08:01:58.227+0000] {processor.py:186} INFO - Started process (PID=958) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:01:58.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:01:58.231+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:58.230+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:01:58.323+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:01:58.314+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:01:58.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:01:58.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.142 seconds
[2024-08-18T08:02:29.125+0000] {processor.py:186} INFO - Started process (PID=976) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:02:29.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:02:29.128+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:29.127+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:02:29.178+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:02:29.169+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:02:29.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:02:29.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.099 seconds
[2024-08-18T08:03:00.532+0000] {processor.py:186} INFO - Started process (PID=994) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:03:00.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:03:00.536+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:00.536+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:03:00.644+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:00.629+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:03:00.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:03:00.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.198 seconds
[2024-08-18T08:03:31.887+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:03:31.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:03:31.891+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:31.890+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:03:31.994+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:03:31.979+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:03:31.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:03:32.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.198 seconds
[2024-08-18T08:04:03.144+0000] {processor.py:186} INFO - Started process (PID=1030) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:04:03.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:04:03.147+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:03.147+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:04:03.206+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:03.198+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:04:03.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:04:03.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.140 seconds
[2024-08-18T08:04:33.885+0000] {processor.py:186} INFO - Started process (PID=1048) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:04:33.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:04:33.889+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:33.889+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:04:33.991+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:04:33.976+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:04:33.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:04:34.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.195 seconds
[2024-08-18T08:05:05.176+0000] {processor.py:186} INFO - Started process (PID=1066) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:05:05.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:05:05.180+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:05.180+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:05:05.259+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:05.249+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:05:05.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:05:05.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.162 seconds
[2024-08-18T08:05:37.432+0000] {processor.py:186} INFO - Started process (PID=1084) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:05:37.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:05:37.435+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:37.435+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:05:37.513+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:05:37.507+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:05:37.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:05:37.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.162 seconds
[2024-08-18T08:06:10.654+0000] {processor.py:186} INFO - Started process (PID=1103) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:06:10.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:06:10.659+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:10.658+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:06:10.742+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:10.734+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:06:10.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:06:10.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.166 seconds
[2024-08-18T08:06:43.114+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:06:43.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:06:43.120+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:43.119+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:06:43.210+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:06:43.197+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:06:43.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:06:43.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.181 seconds
[2024-08-18T08:07:15.377+0000] {processor.py:186} INFO - Started process (PID=1139) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:07:15.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:07:15.381+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:15.380+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:07:15.464+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:15.455+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:07:15.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:07:15.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.163 seconds
[2024-08-18T08:07:48.432+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:07:48.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:07:48.436+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:48.435+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:07:48.534+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:07:48.520+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:07:48.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:07:48.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.180 seconds
[2024-08-18T08:08:20.167+0000] {processor.py:186} INFO - Started process (PID=1175) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:08:20.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:08:20.171+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:20.171+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:08:20.238+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:20.231+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:08:20.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:08:20.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.151 seconds
[2024-08-18T08:08:51.718+0000] {processor.py:186} INFO - Started process (PID=1193) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:08:51.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:08:51.722+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:51.721+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:08:51.818+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:08:51.805+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:08:51.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:08:51.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.185 seconds
[2024-08-18T08:09:23.969+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:09:23.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:09:23.973+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:23.973+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:09:24.069+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:24.057+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:09:24.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:09:24.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.190 seconds
[2024-08-18T08:09:56.074+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:09:56.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:09:56.077+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:56.076+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:09:56.155+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:09:56.140+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:09:56.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:09:56.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.173 seconds
[2024-08-18T08:10:27.463+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:10:27.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:10:27.467+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:27.467+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:10:27.559+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:27.548+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:10:27.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:10:27.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.172 seconds
[2024-08-18T08:10:58.036+0000] {processor.py:186} INFO - Started process (PID=1265) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:10:58.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:10:58.040+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:58.039+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:10:58.133+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:10:58.118+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:10:58.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:10:58.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.186 seconds
[2024-08-18T08:11:30.153+0000] {processor.py:186} INFO - Started process (PID=1283) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:11:30.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:11:30.156+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:30.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:11:30.227+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:11:30.218+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:11:30.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:11:30.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.147 seconds
[2024-08-18T08:12:04.471+0000] {processor.py:186} INFO - Started process (PID=1302) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:12:04.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:12:04.483+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:04.482+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:12:04.606+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:04.590+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:12:04.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:12:04.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.258 seconds
[2024-08-18T08:12:35.943+0000] {processor.py:186} INFO - Started process (PID=1321) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:12:35.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:12:35.947+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:35.946+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:12:36.034+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:12:36.023+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:12:36.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:12:36.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.171 seconds
[2024-08-18T08:13:09.671+0000] {processor.py:186} INFO - Started process (PID=1339) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:13:09.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:13:09.676+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:09.674+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:13:09.768+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:09.755+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:13:09.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:13:09.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.192 seconds
[2024-08-18T08:13:53.932+0000] {processor.py:186} INFO - Started process (PID=1360) to work on /opt/airflow/dags/producer.py
[2024-08-18T08:13:53.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-08-18T08:13:53.936+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:53.936+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-08-18T08:13:54.038+0000] {logging_mixin.py:190} INFO - [2024-08-18T08:13:54.022+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 15, in <module>
    endpoint=Variable.get("web_api_key"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable web_api_key does not exist'
[2024-08-18T08:13:54.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-08-18T08:13:54.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/producer.py took 0.270 seconds
